services:
  postgres:
    image: postgres:16
    container_name: nest-postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nest_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
